### ISSUE TITLE
Remote Redis

### ISSUE THREAD

**Issue by MonaxGT** [yetship/celerybeatredis#12]
Hello! 

I tried to use remote redis docker, but all my attempts were unsuccessful. 
All times when i run celerybeatredis, celery  beat use localhost instead remote address (redis://redis:6379).

```
celery beat v4.1.0 (latentcall) is starting.
__    -    ... __   -        _
LocalTime -> 2018-01-06 18:46:45
Configuration ->
    . broker -> redis://redis:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> redisbeat.scheduler.RedisScheduler
    . db -> redis://localhost:6379, key -> celery:beat:order_tasks
    . logfile -> [stderr]@%WARNING
```

but celery worker use right address of redis.

I try in docker: 
```
environment:
      CELERY_BROKER_URL: 'redis://redis:6379'
      CELERY_RESULT_BACKEND: 'redis://redis:6379'
      CELERY_TASK_SERIALIZER: 'json'
      CELERY_RESULT_SERIALIZER: 'json'
      CELERY_RESULT_BACKEND: "redis"
      CELERY_REDIS_HOST: "redis"
      CELERY_REDIS_PORT: 6379
      CELERY_REDIS_DB: 0
      CELERY_BEAT_SCHEDULER: 'redisbeat.RedisScheduler'
      CELERY_REDIS_SCHEDULER_URL: 'redis://redis:6379/1'
      CELERY_REDIS_SCHEDULER_KEY: 'celery:beat:order_test'
      WAIT_HOSTS: redis:6379, elasticsearch:9200
```

Try in .py file like this:
```
CELERY_BEAT_SCHEDULER = 'redisbeat.RedisScheduler'
CELERY_REDIS_SCHEDULER_URL = 'redis://redis:6379'
CELERY_REDIS_SCHEDULER_KEY = 'celery:beat:order_test'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = "redis"
CELERY_REDIS_HOST = "redis"
CELERY_REDIS_PORT = 6379
CELERY_REDIS_DB = 1
CELERY_BROKER_URL = 'redis://redis:6379/0'
BROKER_URL = CELERY_BROKER_URL
CELERY_RESULT_BACKEND = 'redis://redis:6379/1'

app = Celery('test', backend='redis://{}'.format(REDIS),
             broker='redis://{}'.format(REDIS))

app.conf.broker_url = 'redis://redis:6379/0'
app.conf.result_backend = 'redis://redis:6379/0'
```
I also try use this settings config file celery and use --config option on celery beat.

How i can use remote redis for celerybeatredis ?
